# ==========================
# DATA DE ENTRENAMIENTO
# ==========================
TRAIN_DATA = [
    ('El contrato será válido hasta el 2027.', {'entities': [(33, 37, 'DATE')]}),
    ('El comprador deberá pagar antes del 15 de julio de 2025.', {'entities': [(36, 55, 'DATE')]}),
    ('La cláusula entrará en vigencia el 1/01/2027.', {'entities': [(35, 44, 'DATE')]}),
    ('El pago inicial vence el 15 de julio de 2025.', {'entities': [(25, 44, 'DATE')]}),
    ('El contrato será válido hasta el 30/03/2025.', {'entities': [(33, 43, 'DATE')]}),
    ('El comprador deberá pagar antes del 2027.', {'entities': [(36, 40, 'DATE')]}),
    ('La reunión se llevará a cabo el ayer.', {'entities': [(32, 36, 'DATE')]}),
    ('El contrato se firmará el junio 2026.', {'entities': [(26, 36, 'DATE')]}),
    ('La escritura se inscribirá el 2028-11-05.', {'entities': [(30, 40, 'DATE')]}),
    ('El pago inicial vence el junio 2026.', {'entities': [(25, 35, 'DATE')]}),
    ('La cláusula entrará en vigencia el junio 2026.', {'entities': [(35, 45, 'DATE')]}),
    ('La cancelación se realizará el julio de 2029.', {'entities': [(31, 44, 'DATE')]}),
    ('La reunión se llevará a cabo el mañana.', {'entities': [(32, 38, 'DATE')]}),
    ('Se fija como fecha de entrega el julio de 2029.', {'entities': [(33, 46, 'DATE')]}),
    ('La cláusula entrará en vigencia el 2025.', {'entities': [(35, 39, 'DATE')]}),
    ('El contrato se firmará el junio 2026.', {'entities': [(26, 36, 'DATE')]}),
    ('La escritura se inscribirá el 10 de mayo de 2025.', {'entities': [(30, 48, 'DATE')]}),
    ('La cláusula entrará en vigencia el marzo de 2025.', {'entities': [(35, 48, 'DATE')]}),
    ('La cláusula entrará en vigencia el 20 de diciembre de 2025.', {'entities': [(35, 58, 'DATE')]}),
    ('La cancelación se realizará el 1 de febrero de 2025.', {'entities': [(31, 51, 'DATE')]}),
    ('El contrato se firmará el 15 de julio de 2025.', {'entities': [(26, 45, 'DATE')]}),
    ('Se fija como fecha de entrega el 2027.', {'entities': [(33, 37, 'DATE')]}),
    ('La escritura se inscribirá el mañana.', {'entities': [(30, 36, 'DATE')]}),
    ('La escritura se inscribirá el julio de 2029.', {'entities': [(30, 43, 'DATE')]}),
    ('El contrato se firmará el julio de 2029.', {'entities': [(26, 39, 'DATE')]}),
    ('El arrendamiento terminará el 30/03/2025.', {'entities': [(30, 40, 'DATE')]}),
    ('La reunión se llevará a cabo el ayer.', {'entities': [(32, 36, 'DATE')]}),
    ('El arrendamiento terminará el primer día hábil de enero de 2026.', {'entities': [(30, 63, 'DATE')]}),
    ('El arrendamiento terminará el marzo de 2025.', {'entities': [(30, 43, 'DATE')]}),
    ('La reunión se llevará a cabo el 2028-11-05.', {'entities': [(32, 42, 'DATE')]}),
    ('El arrendamiento terminará el julio de 2029.', {'entities': [(30, 43, 'DATE')]}),
    ('La reunión se llevará a cabo el 10 de mayo de 2025.', {'entities': [(32, 50, 'DATE')]}),
    ('La cláusula entrará en vigencia el 2025-04-01.', {'entities': [(35, 45, 'DATE')]}),
    ('El comprador deberá pagar antes del 2025-04-01.', {'entities': [(36, 46, 'DATE')]}),
    ('El arrendamiento terminará el 10 de mayo de 2025.', {'entities': [(30, 48, 'DATE')]}),
    ('La reunión se llevará a cabo el ayer.', {'entities': [(32, 36, 'DATE')]}),
    ('El comprador deberá pagar antes del marzo de 2025.', {'entities': [(36, 49, 'DATE')]}),
    ('El contrato será válido hasta el 1/01/2027.', {'entities': [(33, 42, 'DATE')]}),
    ('El pago inicial vence el 1/01/2027.', {'entities': [(25, 34, 'DATE')]}),
    ('La reunión se llevará a cabo el 2025-04-01.', {'entities': [(32, 42, 'DATE')]}),
    ('La reunión se llevará a cabo el 2025.', {'entities': [(32, 36, 'DATE')]}),
    ('El arrendamiento terminará el 30/03/2025.', {'entities': [(30, 40, 'DATE')]}),
    ('El arrendamiento terminará el marzo de 2025.', {'entities': [(30, 43, 'DATE')]}),
    ('El contrato se firmará el ayer.', {'entities': [(26, 30, 'DATE')]}),
    ('La escritura se inscribirá el primer día hábil de enero de 2026.', {'entities': [(30, 63, 'DATE')]}),
    ('La cláusula entrará en vigencia el 2025-04-01.', {'entities': [(35, 45, 'DATE')]}),
    ('La reunión se llevará a cabo el mañana.', {'entities': [(32, 38, 'DATE')]}),
    ('El arrendamiento terminará el 31-12-2026.', {'entities': [(30, 40, 'DATE')]}),
    ('El contrato se firmará el 20 de diciembre de 2025.', {'entities': [(26, 49, 'DATE')]}),
    ('El contrato será válido hasta el mañana.', {'entities': [(33, 39, 'DATE')]}),
    ('El contrato será válido hasta el mañana.', {'entities': [(33, 39, 'DATE')]}),
    ('El contrato será válido hasta el agosto 2030.', {'entities': [(33, 44, 'DATE')]}),
    ('El pago inicial vence el primer día hábil de enero de 2026.', {'entities': [(25, 58, 'DATE')]}),
    ('El comprador deberá pagar antes del ayer.', {'entities': [(36, 40, 'DATE')]}),
    ('El pago inicial vence el 2027.', {'entities': [(25, 29, 'DATE')]}),
    ('La escritura se inscribirá el 2027.', {'entities': [(30, 34, 'DATE')]}),
    ('La cláusula entrará en vigencia el agosto 2030.', {'entities': [(35, 46, 'DATE')]}),
    ('El contrato será válido hasta el ayer.', {'entities': [(33, 37, 'DATE')]}),
    ('El contrato será válido hasta el 15 de enero de 2025.', {'entities': [(33, 52, 'DATE')]}),
    ('El comprador deberá pagar antes del 2025-04-01.', {'entities': [(36, 46, 'DATE')]}),
    ('El contrato será válido hasta el 15 de julio de 2025.', {'entities': [(33, 52, 'DATE')]}),
    ('El arrendamiento terminará el 2025.', {'entities': [(30, 34, 'DATE')]}),
    ('La cláusula entrará en vigencia el hoy.', {'entities': [(35, 38, 'DATE')]}),
    ('Se fija como fecha de entrega el 2025.', {'entities': [(33, 37, 'DATE')]}),
    ('La cancelación se realizará el 15 de enero de 2025.', {'entities': [(31, 50, 'DATE')]}),
    ('La escritura se inscribirá el agosto 2030.', {'entities': [(30, 41, 'DATE')]}),
    ('La cláusula entrará en vigencia el junio 2026.', {'entities': [(35, 45, 'DATE')]}),
    ('La escritura se inscribirá el 15 de julio de 2025.', {'entities': [(30, 49, 'DATE')]}),
    ('La cláusula entrará en vigencia el 2025.', {'entities': [(35, 39, 'DATE')]}),
    ('Se fija como fecha de entrega el 2025.', {'entities': [(33, 37, 'DATE')]}),
    ('La cláusula entrará en vigencia el 2025-04-01.', {'entities': [(35, 45, 'DATE')]}),
    ('El arrendamiento terminará el 15 de julio de 2025.', {'entities': [(30, 49, 'DATE')]}),
    ('El arrendamiento terminará el marzo de 2025.', {'entities': [(30, 43, 'DATE')]}),
    ('La cláusula entrará en vigencia el mañana.', {'entities': [(35, 41, 'DATE')]}),
    ('El contrato será válido hasta el 2025.', {'entities': [(33, 37, 'DATE')]}),
    ('La cláusula entrará en vigencia el marzo de 2025.', {'entities': [(35, 48, 'DATE')]}),
    ('La cláusula entrará en vigencia el 20 de diciembre de 2025.', {'entities': [(35, 58, 'DATE')]}),
    ('La cancelación se realizará el 15 de julio de 2025.', {'entities': [(31, 50, 'DATE')]}),
    ('El pago inicial vence el 15 de enero de 2025.', {'entities': [(25, 44, 'DATE')]}),
    ('Se fija como fecha de entrega el agosto 2030.', {'entities': [(33, 44, 'DATE')]}),
    ('El arrendamiento terminará el hoy.', {'entities': [(30, 33, 'DATE')]}),
    ('El contrato se firmará el 1/01/2027.', {'entities': [(26, 35, 'DATE')]}),
    ('La cancelación se realizará el 1 de febrero de 2025.', {'entities': [(31, 51, 'DATE')]}),
    ('La reunión se llevará a cabo el 1 de febrero de 2025.', {'entities': [(32, 52, 'DATE')]}),
    ('La reunión se llevará a cabo el 2025.', {'entities': [(32, 36, 'DATE')]}),
    ('La escritura se inscribirá el ayer.', {'entities': [(30, 34, 'DATE')]}),
    ('El arrendamiento terminará el 1 de febrero de 2025.', {'entities': [(30, 50, 'DATE')]}),
    ('La reunión se llevará a cabo el primer día hábil de enero de 2026.', {'entities': [(32, 65, 'DATE')]}),
    ('La cláusula entrará en vigencia el 2025-04-01.', {'entities': [(35, 45, 'DATE')]}),
    ('El arrendamiento terminará el hoy.', {'entities': [(30, 33, 'DATE')]}),
    ('El contrato será válido hasta el 2025-04-01.', {'entities': [(33, 43, 'DATE')]}),
    ('El contrato se firmará el primer día hábil de enero de 2026.', {'entities': [(26, 59, 'DATE')]}),
    ('El comprador deberá pagar antes del 10 de mayo de 2025.', {'entities': [(36, 54, 'DATE')]}),
    ('La cancelación se realizará el marzo de 2025.', {'entities': [(31, 44, 'DATE')]}),
    ('Se fija como fecha de entrega el ayer.', {'entities': [(33, 37, 'DATE')]}),
    ('Se fija como fecha de entrega el 30/03/2025.', {'entities': [(33, 43, 'DATE')]}),
    ('El contrato será válido hasta el mañana.', {'entities': [(33, 39, 'DATE')]}),
    ('La reunión se llevará a cabo el 10 de mayo de 2025.', {'entities': [(32, 50, 'DATE')]}),
    ('La cancelación se realizará el julio de 2029.', {'entities': [(31, 44, 'DATE')]}),
    ('El comprador deberá pagar antes del 1/01/2027.', {'entities': [(36, 45, 'DATE')]}),
    ('El vendedor recibirá un monto de veinte mil dólares.', {'entities': [(33, 51, 'MONEY')]}),
    ('El precio acordado fue de US$ 250,000.', {'entities': [(26, 37, 'MONEY')]}),
    ('La segunda cuota será por un monto de US$ 50,000.00.', {'entities': [(38, 51, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 250,000.', {'entities': [(35, 46, 'MONEY')]}),
    ('La segunda cuota será por un monto de veinte mil dólares.', {'entities': [(38, 56, 'MONEY')]}),
    ('El vendedor recibirá un monto de USD 75,000.00.', {'entities': [(33, 46, 'MONEY')]}),
    ('La segunda cuota será por un monto de S/ 5,000.00.', {'entities': [(38, 49, 'MONEY')]}),
    ('El saldo pendiente asciende a US$ 250,000.', {'entities': [(30, 41, 'MONEY')]}),
    ('El saldo pendiente asciende a S/ 15,000.', {'entities': [(30, 39, 'MONEY')]}),
    ('El valor de la operación asciende a S/ 1,250.75.', {'entities': [(36, 47, 'MONEY')]}),
    ('El precio acordado fue de USD 75,000.00.', {'entities': [(26, 39, 'MONEY')]}),
    ('El valor de la operación asciende a trescientos mil soles.', {'entities': [(36, 57, 'MONEY')]}),
    ('La segunda cuota será por un monto de quinientos mil soles.', {'entities': [(38, 58, 'MONEY')]}),
    ('El precio total del inmueble es de S/ 2,000.', {'entities': [(35, 43, 'MONEY')]}),
    ('El comprador entregará un adelanto de veinte mil dólares.', {'entities': [(38, 56, 'MONEY')]}),
    ('El precio total del inmueble es de PEN 120,000.', {'entities': [(35, 46, 'MONEY')]}),
    ('El pago parcial corresponde a USD 75,000.00.', {'entities': [(30, 43, 'MONEY')]}),
    ('El saldo pendiente asciende a US$ 1,500,000.00.', {'entities': [(30, 46, 'MONEY')]}),
    ('El comprador entregará un adelanto de USD 75,000.00.', {'entities': [(38, 51, 'MONEY')]}),
    ('El comprador entregará US$ 50,000.00.', {'entities': [(23, 36, 'MONEY')]}),
    ('El vendedor recibirá un monto de US$ 100,000 (cien mil dólares americanos).', {'entities': [(33, 74, 'MONEY')]}),
    ('El pago parcial corresponde a veinte mil dólares.', {'entities': [(30, 48, 'MONEY')]}),
    ('El precio total del inmueble es de veinte mil dólares.', {'entities': [(35, 53, 'MONEY')]}),
    ('El comprador entregará un adelanto de trescientos mil soles.', {'entities': [(38, 59, 'MONEY')]}),
    ('El comprador entregará US$ 50,000.00.', {'entities': [(23, 36, 'MONEY')]}),
    ('El vendedor recibirá un monto de S/ 15,000.', {'entities': [(33, 42, 'MONEY')]}),
    ('El saldo pendiente asciende a S/ 350,000.00.', {'entities': [(30, 43, 'MONEY')]}),
    ('El valor de la operación asciende a S/ 15,000.', {'entities': [(36, 45, 'MONEY')]}),
    ('El comprador entregará S/ 350,000.00.', {'entities': [(23, 36, 'MONEY')]}),
    ('El precio total del inmueble es de S/ 350,000.00.', {'entities': [(35, 48, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 50,000.00.', {'entities': [(35, 48, 'MONEY')]}),
    ('El valor de la operación asciende a veinte mil dólares.', {'entities': [(36, 54, 'MONEY')]}),
    ('El precio total del inmueble es de S/ 1,250.75.', {'entities': [(35, 46, 'MONEY')]}),
    ('El pago parcial corresponde a S/ 2,000.', {'entities': [(30, 38, 'MONEY')]}),
    ('El comprador entregará un adelanto de US$ 1,234.56.', {'entities': [(38, 50, 'MONEY')]}),
    ('El valor de la operación asciende a US$ 100,000 (cien mil dólares americanos).', {'entities': [(36, 77, 'MONEY')]}),
    ('El valor de la operación asciende a US$ 250,000.', {'entities': [(36, 47, 'MONEY')]}),
    ('El comprador entregará un adelanto de PEN 120,000.', {'entities': [(38, 49, 'MONEY')]}),
    ('El valor de la operación asciende a US$ 1,500,000.00.', {'entities': [(36, 52, 'MONEY')]}),
    ('El pago parcial corresponde a quinientos mil soles.', {'entities': [(30, 50, 'MONEY')]}),
    ('El precio acordado fue de S/ 1,250.75.', {'entities': [(26, 37, 'MONEY')]}),
    ('El comprador entregará US$ 100,000 (cien mil dólares americanos).', {'entities': [(23, 64, 'MONEY')]}),
    ('El precio total del inmueble es de S/ 5,000.00.', {'entities': [(35, 46, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 100,000 (cien mil dólares americanos).', {'entities': [(35, 76, 'MONEY')]}),
    ('El precio acordado fue de S/ 500.', {'entities': [(26, 32, 'MONEY')]}),
    ('Se fija una penalidad de S/ 99.99 en caso de incumplimiento.', {'entities': [(25, 33, 'MONEY')]}),
    ('El comprador entregará US$ 50,000.00.', {'entities': [(23, 36, 'MONEY')]}),
    ('El precio acordado fue de US$ 1,234.56.', {'entities': [(26, 38, 'MONEY')]}),
    ('El comprador entregará trescientos mil soles.', {'entities': [(23, 44, 'MONEY')]}),
    ('El saldo pendiente asciende a S/ 15,000.', {'entities': [(30, 39, 'MONEY')]}),
    ('El comprador entregará S/ 99.99.', {'entities': [(23, 31, 'MONEY')]}),
    ('El pago parcial corresponde a S/ 2,000.', {'entities': [(30, 38, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 50,000.00.', {'entities': [(35, 48, 'MONEY')]}),
    ('El comprador entregará un adelanto de trescientos mil soles.', {'entities': [(38, 59, 'MONEY')]}),
    ('El precio acordado fue de S/ 15,000.', {'entities': [(26, 35, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 1,234.56.', {'entities': [(35, 47, 'MONEY')]}),
    ('Se fija una penalidad de S/ 350,000.00 en caso de incumplimiento.', {'entities': [(25, 38, 'MONEY')]}),
    ('El precio acordado fue de trescientos mil soles.', {'entities': [(26, 47, 'MONEY')]}),
    ('El precio acordado fue de S/ 350,000.00.', {'entities': [(26, 39, 'MONEY')]}),
    ('El comprador entregará S/ 15,000.', {'entities': [(23, 32, 'MONEY')]}),
    ('El comprador entregará un adelanto de S/ 500.', {'entities': [(38, 44, 'MONEY')]}),
    ('La segunda cuota será por un monto de US$ 1,234.56.', {'entities': [(38, 50, 'MONEY')]}),
    ('El vendedor recibirá un monto de PEN 120,000.', {'entities': [(33, 44, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 100,000 (cien mil dólares americanos).', {'entities': [(35, 76, 'MONEY')]}),
    ('El precio total del inmueble es de S/ 5,000.00.', {'entities': [(35, 46, 'MONEY')]}),
    ('Se fija una penalidad de S/ 2,000 en caso de incumplimiento.', {'entities': [(25, 33, 'MONEY')]}),
    ('El precio total del inmueble es de ciento veinte mil dólares.', {'entities': [(35, 60, 'MONEY')]}),
    ('Se fija una penalidad de US$ 1,500,000.00 en caso de incumplimiento.', {'entities': [(25, 41, 'MONEY')]}),
    ('El vendedor recibirá un monto de S/ 500.', {'entities': [(33, 39, 'MONEY')]}),
    ('El pago parcial corresponde a trescientos mil soles.', {'entities': [(30, 51, 'MONEY')]}),
    ('La segunda cuota será por un monto de S/ 2,000.', {'entities': [(38, 46, 'MONEY')]}),
    ('El comprador entregará un adelanto de PEN 120,000.', {'entities': [(38, 49, 'MONEY')]}),
    ('El comprador entregará un adelanto de S/ 500.', {'entities': [(38, 44, 'MONEY')]}),
    ('El pago parcial corresponde a S/ 15,000.', {'entities': [(30, 39, 'MONEY')]}),
    ('Se fija una penalidad de USD 75,000.00 en caso de incumplimiento.', {'entities': [(25, 38, 'MONEY')]}),
    ('El comprador entregará S/ 500.', {'entities': [(23, 29, 'MONEY')]}),
    ('El comprador entregará S/ 5,000.00.', {'entities': [(23, 34, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 1,234.56.', {'entities': [(35, 47, 'MONEY')]}),
    ('El precio acordado fue de S/ 1,250.75.', {'entities': [(26, 37, 'MONEY')]}),
    ('El precio acordado fue de US$ 50,000.00.', {'entities': [(26, 39, 'MONEY')]}),
    ('La segunda cuota será por un monto de S/ 2,000.', {'entities': [(38, 46, 'MONEY')]}),
    ('El precio acordado fue de quinientos mil soles.', {'entities': [(26, 46, 'MONEY')]}),
    ('El precio acordado fue de S/ 99.99.', {'entities': [(26, 34, 'MONEY')]}),
    ('El comprador entregará un adelanto de US$ 250,000.', {'entities': [(38, 49, 'MONEY')]}),
    ('El precio total del inmueble es de US$ 250,000.', {'entities': [(35, 46, 'MONEY')]}),
    ('El precio acordado fue de S/ 5,000.00.', {'entities': [(26, 37, 'MONEY')]}),
    ('El comprador entregará S/ 15,000.', {'entities': [(23, 32, 'MONEY')]}),
    ('Se fija una penalidad de USD 75,000.00 en caso de incumplimiento.', {'entities': [(25, 38, 'MONEY')]}),
    ('El precio acordado fue de S/ 1,250.75.', {'entities': [(26, 37, 'MONEY')]}),
    ('El pago parcial corresponde a S/ 350,000.00.', {'entities': [(30, 43, 'MONEY')]}),
    ('El comprador entregará un adelanto de S/ 1,250.75.', {'entities': [(38, 49, 'MONEY')]}),
    ('Se fija una penalidad de S/ 99.99 en caso de incumplimiento.', {'entities': [(25, 33, 'MONEY')]}),
    ('El vendedor recibirá un monto de quinientos mil soles.', {'entities': [(33, 53, 'MONEY')]}),
    ('Se fija una penalidad de US$ 3,450 en caso de incumplimiento.', {'entities': [(25, 34, 'MONEY')]}),
    ('El comprador entregará US$ 1,234.56.', {'entities': [(23, 35, 'MONEY')]}),
    ('El valor de la operación asciende a S/ 350,000.00.', {'entities': [(36, 49, 'MONEY')]}),
    ('El valor de la operación asciende a USD 200,000.', {'entities': [(36, 47, 'MONEY')]}),
    ('El precio total del inmueble es de S/ 1,250.75.', {'entities': [(35, 46, 'MONEY')]}),
    ('El valor de la operación asciende a S/ 5,000.00.', {'entities': [(36, 47, 'MONEY')]}),
    ('El vendedor recibirá un monto de US$ 1,234.56.', {'entities': [(33, 45, 'MONEY')]}),
]
